A = rand(3,4)
AIP.check_sameinds(A, A)
@test_throws DimensionMismatch AIP.check_sameinds(A, A')
@test isa(AIP.storageorder(A), AIP.FirstToLast)
R = reshape(A, (2,3,2))
@test isa(AIP.storageorder(R), AIP.FirstToLast)
S = sub(A, 1:3, 1:4)
R = reshape(S, (2,3,2))
@test isa(AIP.storageorder(R), AIP.FirstToLast)
B = PermutedDimsArray(A, [2,1])
@test isa(AIP.storageorder(B), AIP.OtherOrder{(2,1)})
R = reshape(B, (2,2,3))
@test isa(AIP.storageorder(R), AIP.NoOrder)
